name: Build and Test

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Java JDK
        uses: actions/setup-java@v3
        with:
          java-version: "17"
          distribution: "temurin"

      - name: Build
        working-directory: ./java/src
        run: ./lab7/generator/ArrayListGenerator.java ./lab7/generator/ArrayListGeneratorRules.java ./lab7/convertor/ToStringConvertor.java ./lab7/convertor/ToStringConvertorRules.java ./lab7/finder/ArrayListFinder.java ./lab7/finder/ArrayListFinderRules.java ./lab7/Main.java
      - name: Test
        working-directory: ./java
        run: |
          javac -cp "./junit/junit-platform-console-standalone-1.9.0.jar" ./lab7/generator/ArrayListGenerator.java ./lab7/generator/ArrayListGeneratorRules.java ./lab7/testsArrayListGeneratorTests.java
          java -jar ./junit/junit-platform-console-standalone-1.9.0.jar -cp "./src" --select-class lab7.tests.ArrayListGeneratorTests 
          javac -cp "./junit/junit-platform-console-standalone-1.9.0.jar" ./src/lab7/convertor/ToStringConvertor.java ./src/lab7/convertor/ToStringConvertorRules.java ./src/lab7/tests/ToStringConvertorTests.java
          java -jar ./junit/junit-platform-console-standalone-1.9.0.jar -cp "./src" --select-class lab7.tests.ToStringConvertor      
          javac -cp "./junit/junit-platform-console-standalone-1.9.0.jar" ./src/lab7/finder/ArrayListFinder.java ./src/lab7/finder/ArrayListFinderRules.java ./src/lab7/tests/ArrayListFinderTests.java
          java -jar ./junit/junit-platform-console-standalone-1.9.0.jar -cp "./src" --select-class lab7.tests.ArrayListFinderTests              